import * as THREE from 'three'
import JSZip from 'jszip'
import { boardFromFen, files, ranks, type Piece } from '../lib/position'
import { chessSetStyles, type ChessSetStyle } from './chessSets'
import { legalPuzzlePositions } from './positions'

const meshFor = (piece: Piece, style: ChessSetStyle) => {
  const dark = piece === piece.toLowerCase(); const material = new THREE.MeshStandardMaterial({ color: dark ? style.dark : style.light, roughness: style.material==='marble' ? .22 : .42, metalness: style.material==='marble' ? .08 : 0 })
  const group=new THREE.Group(); const height=piece.toLowerCase()==='k'?1.25:piece.toLowerCase()==='q'?1.15:.95
  const base=new THREE.Mesh(new THREE.CylinderGeometry(.28,.34,.13,32),material);base.position.y=.07;group.add(base)
  const body=new THREE.Mesh(new THREE.LatheGeometry([new THREE.Vector2(.17,.13),new THREE.Vector2(.13,height*.42),new THREE.Vector2(style.silhouette==='minimal'?.18:.27,height*.66),new THREE.Vector2(.14,height*.82)],32),material);body.position.y=.13;group.add(body)
  const letter=piece.toLowerCase(); const top=letter==='p'?new THREE.SphereGeometry(.18,24,16):letter==='n'?new THREE.ConeGeometry(.24,.44,5):letter==='r'?new THREE.CylinderGeometry(.24,.24,.18,4):letter==='b'?new THREE.SphereGeometry(.2,24,16):new THREE.SphereGeometry(.25,24,16)
  const crown=new THREE.Mesh(top,material);crown.position.y=height;group.add(crown)
  if(letter==='k'){const cross=new THREE.Mesh(new THREE.BoxGeometry(.08,.28,.08),material);cross.position.y=height+.22;group.add(cross);const arm=new THREE.Mesh(new THREE.BoxGeometry(.28,.08,.08),material);arm.position.y=height+.25;group.add(arm)}
  group.castShadow=true;group.receiveShadow=true;return group
}
const render = (fen:string, style:ChessSetStyle, seed:number) => { const canvas=document.createElement('canvas');canvas.width=640;canvas.height=640;const renderer=new THREE.WebGLRenderer({canvas,antialias:true,preserveDrawingBuffer:true});renderer.setSize(640,640);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;const scene=new THREE.Scene();scene.background=new THREE.Color('#c9c1aa');const camera=new THREE.PerspectiveCamera(38,1,.1,100);camera.position.set((seed%3-1)*.7,8.7,6.3);camera.lookAt(0,0,0);scene.add(new THREE.HemisphereLight('#fff4de','#26342d',2));const light=new THREE.DirectionalLight('#fff0ca',3);light.position.set(3+(seed%4),8,4);light.castShadow=true;scene.add(light);for(let y=0;y<8;y++)for(let x=0;x<8;x++){const square=new THREE.Mesh(new THREE.BoxGeometry(1,.14,1),new THREE.MeshStandardMaterial({color:(x+y)%2?'#769656':'#e8d4ae',roughness:.7}));square.position.set(x-3.5,0,y-3.5);square.receiveShadow=true;scene.add(square)}const board=boardFromFen(fen);for(const rank of ranks)for(let col=0;col<files.length;col++){const piece=board[`${files[col]}${rank}`];if(piece){const mesh=meshFor(piece,style);mesh.position.set(col-3.5,.07,7-rank-3.5);scene.add(mesh)}}renderer.render(scene,camera);const png=canvas.toDataURL('image/png').split(',')[1];renderer.dispose();return {png,board} }
export async function downloadDataset(count:number){const zip=new JSZip();const samples=[] as unknown[];const puzzles=legalPuzzlePositions(50);for(let i=0;i<count;i++){const fen=puzzles[i%puzzles.length];const style=chessSetStyles[i%chessSetStyles.length];const rendered=render(fen,style,i+1);const image=`images/sample-${String(i+1).padStart(4,'0')}.png`;zip.file(image,rendered.png,{base64:true});samples.push({image,fen,squares:rendered.board,style,seed:i+1,boardCorners:[[0,0],[640,0],[640,640],[0,640]],lighting:{key:'warm directional',variant:i%4},camera:{projection:'perspective',variant:i%3}})}zip.file('manifest.json',JSON.stringify({version:2,format:'framework-neutral',samples},null,2));const blob=await zip.generateAsync({type:'blob'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='chess-vision-dataset.zip';link.click();URL.revokeObjectURL(link.href)}
